version: "3.9"
networks:
    pmp:
services:
    nginx:
        image: nginx:alpine
        container_name: pmp_nginx
        ports:
            - "82:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - postgres
            - php
        networks:
            - pmp

    postgres:
        container_name: pmp_postgres
        image: postgres:14-alpine
        restart: unless-stopped
        ports:
            - "7432:5432"
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql
        environment:
            - POSTGRES_DB=pmp_db
            - POSTGRES_USERNAME=pmp_user
            - POSTGRES_PASSWORD=pmp_pwd
            - POSTGRES_ROOT_PASSWORD=pmp_pwd_root
            - POSTGRES_HOST_AUTH_METHOD=trust
        networks:
            - pmp
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: pmp_php
        volumes:
            - ./:/var/www/html
        ports:
            - "8081:8081"
        networks:
            - pmp
